[app]
    addr=":8090"
    secret="050dbe0a78e6beb8ae598ec6b1582555"

[api]
    # 部署服务器的域名（用于跨域站点篡改）
    server="https://air.artools.cc"

[mysql]
    host = "localhost"
    port = 3306
    user = "root"
    password = ""
    db = "airplayTV"
    charset = "utf8mb4"
    prefix = ""

[domains]
    # 跨域的m3u8文件以及内容（带协议和断口）
    cors = [
        "https://api.czspp.com:81",
        "https://s2.czspp.com",
        "https://cdn.hls.shenglinyiyang.cn",
        "https://cdn1.hls.shenglinyiyang.cn",
        "https://cdn2.hls.shenglinyiyang.cn",
        "https://cdn3.hls.shenglinyiyang.cn",
        "https://cdn4.hls.shenglinyiyang.cn",
        "https://cdn5.hls.shenglinyiyang.cn",
        "https://abc.xyz",
    ]
    # 直接获取重定向即可播放的视频
    redirect = [
        "https://s1.czspp.com:7721",
        "https://vod.bunediy.com",
        "https://abc.xyz",
    ]
    # 直接可播放
    direct = [
        "https://huxiu-video-baidu.oss-cn-beijing.aliyuncs.com",
        "https://dora-video.hk.svp.tencent-cloud.com",
        "https://lf1-cdn-tos.bytegoofy.com",
        "https://weibo.bh3.com",
        "https://p26-sign.douyinpic.com",
        "https://p1-sign.douyinpic.com",
        "https://p2-sign.douyinpic.com",
        "https://p3-sign.douyinpic.com",
        "https://p4-sign.douyinpic.com",
        "https://p5-sign.douyinpic.com",
        "https://p6-sign.douyinpic.com",
        "https://p7-sign.douyinpic.com",
        "https://p8-sign.douyinpic.com",
        "https://p9-sign.douyinpic.com",
        "https://p10-sign.douyinpic.com",
        "https://p11-sign.douyinpic.com",
        "https://p12-sign.douyinpic.com",
        "https://p13-sign.douyinpic.com",
        "https://p14-sign.douyinpic.com",
        "https://p15-sign.douyinpic.com",
        "https://p16-sign.douyinpic.com",
        "https://p17-sign.douyinpic.com",
        "https://p18-sign.douyinpic.com",
        "https://p19-sign.douyinpic.com",
        "https://p20-sign.douyinpic.com",
        "https://p21-sign.douyinpic.com",
        "https://p22-sign.douyinpic.com",
        "https://p23-sign.douyinpic.com",
        "https://p24-sign.douyinpic.com",
        "https://p25-sign.douyinpic.com",
        "https://sf1-dycdn-tos.pstatp.com",
        "https://sf2-dycdn-tos.pstatp.com",
        "https://sf3-dycdn-tos.pstatp.com",
        "https://sf4-dycdn-tos.pstatp.com",
        "https://sf5-dycdn-tos.pstatp.com",
        "https://sf6-dycdn-tos.pstatp.com",
        "https://sf7-dycdn-tos.pstatp.com",
        "https://sf8-dycdn-tos.pstatp.com",
        "https://sf9-dycdn-tos.pstatp.com",
        "https://sf10-dycdn-tos.pstatp.com",
        "https://sf11-dycdn-tos.pstatp.com",
        "https://sf12-dycdn-tos.pstatp.com",
        "https://sf13-dycdn-tos.pstatp.com",
        "https://sf14-dycdn-tos.pstatp.com",
        "https://sf15-dycdn-tos.pstatp.com",
        "https://sf16-dycdn-tos.pstatp.com",
        "https://sf17-dycdn-tos.pstatp.com",
        "https://sf18-dycdn-tos.pstatp.com",
        "https://sf19-dycdn-tos.pstatp.com",
        "https://abc.xyz"
    ]

    # five源的视频域名(从播放页面处理的视频播放地址的主机)
    fiveVideoHost = [
        "https://m3u8.suoyoudianying.com:2345",
        "https://data.cache.m3u8.lscsfw.com:3395",
        "https://abc.xyz",
    ]

    # 请求需要带referer的数据 "请求地址"="referer地址"
    [domains.referer]
        "https://al.cos20.aliyundrive.asia:81" = "https://www.czspp.com/"
