[app]
    addr=":8089"
    secret="050dbe0a78e6beb8ae598ec6b1582555"

[mysql]
    host = "localhost"
    port = 3306
    user = "root"
    password = ""
    db = "airplayTV"
    charset = "utf8mb4"
    prefix = ""